name: Docker Image CI

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set tag info
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Use Node.js v14
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm ci
      - run: npm run build --if-present
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag meistr/dummy-stock-stream:$IMAGE_TAG
        env:
          IMAGE_TAG: ${{ steps.vars.outputs.tag }}
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        run: |
          docker tag meistr/dummy-stock-stream:$IMAGE_TAG meistr/dummy-stock-stream:latest
          docker push meistr/dummy-stock-stream:$IMAGE_TAG
          docker push meistr/dummy-stock-stream:latest
        env:
          IMAGE_TAG: ${{ steps.vars.outputs.tag }}
